version: "3"
services:
    app:
        image: raptor-app
        container_name: raptor-app
        env_file:
            - docker/.docker.env
        extra_hosts:
            -   "host.docker.internal:host-gateway"
        depends_on:
            - postgres
            - mysql
            - redis
        links:
            - postgres
            - redis
            - mysql
        build:
            context: .
            dockerfile: docker/Dockerfile
        environment:
            CONTAINER_ROLE: app
            XDEBUG_CONFIG: remote_host=host.docker.internal
        volumes:
            - .:/var/www/html
        ports:
            - "${APP_HTTP_PORT}:80"
    mysql:
        image: raptor-mysql
        container_name: raptor-mysql
        build:
            context: .
            dockerfile: docker/MySQLDockerfile
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${MYSQL_DB_NAME}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USERNAME}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "${HOST_MACHINE_MYSQL_PORT}:3306"
    postgres:
        image: postgres:latest
        container_name: raptor-postgres
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - "${HOST_MACHINE_DATABASE_PORT}:5432"
    redis:
        image: redis:6-alpine
        container_name: raptor-redis
        restart: always
        ports:
            - "${HOST_MACHINE_REDIS_PORT}:6379"
        volumes:
            - redis_data:/data
volumes:
    mysql_data:
        driver: "local"
    postgres_data:
        driver: "local"
    redis_data:
        driver: "local"
