version: "3"
services:
    app:
        image: ci4-app
        container_name: ci4-app
        env_file:
            - docker/.docker.env
        extra_hosts:
            -   "host.docker.internal:host-gateway"
        depends_on:
            - main-db
            - cache-db
        links:
            - main-db
            - cache-db
        build:
            context: .
            dockerfile: docker/Dockerfile
        environment:
            CONTAINER_ROLE: app
            XDEBUG_CONFIG: remote_host=host.docker.internal
        volumes:
            - .:/var/www/html
        ports:
            - "${APP_HTTP_PORT}:80"
    main-db:
        image: postgres:14
        container_name: ci4-postgres
        restart: always
        volumes:
            - main_db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - "${HOST_MACHINE_DATABASE_PORT}:5432"
    test-db:
        image: postgres:14
        container_name: ci4-postgres-test
        volumes:
            - test_db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${TEST_DATABASE_NAME}
            POSTGRES_USER: ${TEST_DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${TEST_DATABASE_PASSWORD}
        ports:
            - "${HOST_MACHINE_TEST_DATABASE_PORT}:5432"
    cache-db:
        image: redis:6-alpine
        container_name: ci4-redis
        restart: always
        ports:
            - "${HOST_MACHINE_REDIS_PORT}:6379"
        volumes:
            - cache_db_data:/data
volumes:
    main_db_data:
        driver: "local"
    test_db_data:
        driver: "local"
    cache_db_data:
        driver: "local"